// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_image: dynamic(() => import("./ArticleImage")),
  hero: dynamic(() => import("./Hero")),
  rich_text_block: dynamic(() => import("./RichTextBlock")),
};
