// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  photo_album_photo: dynamic(() => import("./PhotoAlbumPhoto")),
};
