// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  customer_logos: dynamic(() => import("./CustomerLogos")),
  header: dynamic(() => import("./Header")),
};
